spring:
  application:
    name: product-service
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8071}  #CONFIG_SERVER = http://config-server:8071
server:
  port: 8080

#keycloak
keycloak:
  realm: th2501-project
  auth-server-url: http://localhost:8880
  ssl-required: external
  resource: clothes-store
  credentials:
    secret: eduiOHykhrRGmlUlC9xa5LgHxrV2bBYD
  use-resource-role-mappings: false
  bearer-only: true